module.exports = [
	{ value: "afghanistan" },
	{ value: "angola" },
	{ value: "albania" },
	{ value: "united arab emirates" },
	{ value: "argentina" },
	{ value: "armenia" },
	{ value: "antarctica" },
	{ value: "fr. s. antarctic lands" },
	{ value: "australia" },
	{ value: "austria" },
	{ value: "azerbaijan" },
	{ value: "burundi" },
	{ value: "belgium" },
	{ value: "benin" },
	{ value: "burkina faso" },
	{ value: "bangladesh" },
	{ value: "bulgaria" },
	{ value: "bahamas" },
	{ value: "bosnia and herz." },
	{ value: "belarus" },
	{ value: "belize" },
	{ value: "bolivia" },
	{ value: "brazil" },
	{ value: "brunei" },
	{ value: "bhutan" },
	{ value: "botswana" },
	{ value: "central african rep." },
	{ value: "canada" },
	{ value: "switzerland" },
	{ value: "chile" },
	{ value: "china" },
	{ value: "côte d'ivoire" },
	{ value: "cameroon" },
	{ value: "dem. rep. congo" },
	{ value: "congo" },
	{ value: "colombia" },
	{ value: "costa rica" },
	{ value: "cuba" },
	{ value: "n. cyprus" },
	{ value: "cyprus" },
	{ value: "czechia" },
	{ value: "germany" },
	{ value: "djibouti" },
	{ value: "denmark" },
	{ value: "dominican rep." },
	{ value: "algeria" },
	{ value: "ecuador" },
	{ value: "egypt" },
	{ value: "eritrea" },
	{ value: "spain" },
	{ value: "estonia" },
	{ value: "ethiopia" },
	{ value: "finland" },
	{ value: "fiji" },
	{ value: "falkland is." },
	{ value: "france" },
	{ value: "gabon" },
	{ value: "united kingdom" },
	{ value: "georgia" },
	{ value: "ghana" },
	{ value: "guinea" },
	{ value: "gambia" },
	{ value: "guinea-bissau" },
	{ value: "eq. guinea" },
	{ value: "greece" },
	{ value: "greenland" },
	{ value: "guatemala" },
	{ value: "guyana" },
	{ value: "honduras" },
	{ value: "croatia" },
	{ value: "haiti" },
	{ value: "hungary" },
	{ value: "indonesia" },
	{ value: "india" },
	{ value: "ireland" },
	{ value: "iran" },
	{ value: "iraq" },
	{ value: "iceland" },
	{ value: "israel" },
	{ value: "italy" },
	{ value: "jamaica" },
	{ value: "jordan" },
	{ value: "japan" },
	{ value: "kazakhstan" },
	{ value: "kenya" },
	{ value: "kyrgyzstan" },
	{ value: "cambodia" },
	{ value: "south korea" },
	{ value: "kosovo" },
	{ value: "kuwait" },
	{ value: "laos" },
	{ value: "lebanon" },
	{ value: "liberia" },
	{ value: "libya" },
	{ value: "sri lanka" },
	{ value: "lesotho" },
	{ value: "lithuania" },
	{ value: "luxembourg" },
	{ value: "latvia" },
	{ value: "morocco" },
	{ value: "moldova" },
	{ value: "madagascar" },
	{ value: "mexico" },
	{ value: "macedonia" },
	{ value: "mali" },
	{ value: "myanmar" },
	{ value: "montenegro" },
	{ value: "mongolia" },
	{ value: "mozambique" },
	{ value: "mauritania" },
	{ value: "malawi" },
	{ value: "malaysia" },
	{ value: "namibia" },
	{ value: "new caledonia" },
	{ value: "niger" },
	{ value: "nigeria" },
	{ value: "nicaragua" },
	{ value: "netherlands" },
	{ value: "norway" },
	{ value: "nepal" },
	{ value: "new zealand" },
	{ value: "oman" },
	{ value: "pakistan" },
	{ value: "panama" },
	{ value: "peru" },
	{ value: "philippines" },
	{ value: "papua new guinea" },
	{ value: "poland" },
	{ value: "puerto rico" },
	{ value: "north korea" },
	{ value: "portugal" },
	{ value: "paraguay" },
	{ value: "palestine" },
	{ value: "qatar" },
	{ value: "romania" },
	{ value: "russia" },
	{ value: "rwanda" },
	{ value: "w. sahara" },
	{ value: "saudi arabia" },
	{ value: "sudan" },
	{ value: "s. sudan" },
	{ value: "senegal" },
	{ value: "solomon is." },
	{ value: "sierra leone" },
	{ value: "el salvador" },
	{ value: "somaliland" },
	{ value: "somalia" },
	{ value: "serbia" },
	{ value: "suriname" },
	{ value: "slovakia" },
	{ value: "slovenia" },
	{ value: "sweden" },
	{ value: "swaziland" },
	{ value: "syria" },
	{ value: "chad" },
	{ value: "togo" },
	{ value: "thailand" },
	{ value: "tajikistan" },
	{ value: "turkmenistan" },
	{ value: "timor-leste" },
	{ value: "trinidad and tobago" },
	{ value: "tunisia" },
	{ value: "turkey" },
	{ value: "taiwan" },
	{ value: "tanzania" },
	{ value: "uganda" },
	{ value: "ukraine" },
	{ value: "uruguay" },
	{ value: "united states of america" },
	{ value: "uzbekistan" },
	{ value: "venezuela" },
	{ value: "vietnam" },
	{ value: "vanuatu" },
	{ value: "yemen" },
	{ value: "south africa" },
	{ value: "zambia" },
	{ value: "zimbabwe" },
];
