module.exports = [
	{ value: "afghanistan", ISO_A2: "AF" },
	{ value: "angola", ISO_A2: "AO" },
	{ value: "albania", ISO_A2: "AL" },
	{ value: "united arab emirates", ISO_A2: "AE" },
	{ value: "argentina", ISO_A2: "AR" },
	{ value: "armenia", ISO_A2: "AM" },
	{ value: "antarctica", ISO_A2: "AQ" },
	{ value: "fr. s. antarctic lands", ISO_A2: "TF" },
	{ value: "australia", ISO_A2: "AU" },
	{ value: "austria", ISO_A2: "AT" },
	{ value: "azerbaijan", ISO_A2: "AZ" },
	{ value: "burundi", ISO_A2: "BI" },
	{ value: "belgium", ISO_A2: "BE" },
	{ value: "benin", ISO_A2: "BJ" },
	{ value: "burkina faso", ISO_A2: "BF" },
	{ value: "bangladesh", ISO_A2: "BD" },
	{ value: "bulgaria", ISO_A2: "BG" },
	{ value: "bahamas", ISO_A2: "BS" },
	{ value: "bosnia and herz.", ISO_A2: "BA" },
	{ value: "belarus", ISO_A2: "BY" },
	{ value: "belize", ISO_A2: "BZ" },
	{ value: "bolivia", ISO_A2: "BO" },
	{ value: "brazil", ISO_A2: "BR" },
	{ value: "brunei", ISO_A2: "BN" },
	{ value: "bhutan", ISO_A2: "BT" },
	{ value: "botswana", ISO_A2: "BW" },
	{ value: "central african rep.", ISO_A2: "CF" },
	{ value: "canada", ISO_A2: "CA" },
	{ value: "switzerland", ISO_A2: "CH" },
	{ value: "chile", ISO_A2: "CL" },
	{ value: "china", ISO_A2: "CN" },
	{ value: "côte d'ivoire", ISO_A2: "CI" },
	{ value: "cameroon", ISO_A2: "CM" },
	{ value: "dem. rep. congo", ISO_A2: "CD" },
	{ value: "congo", ISO_A2: "CG" },
	{ value: "colombia", ISO_A2: "CO" },
	{ value: "costa rica", ISO_A2: "CR" },
	{ value: "cuba", ISO_A2: "CU" },
	{ value: "n. cyprus", ISO_A2: "-99" },
	{ value: "cyprus", ISO_A2: "CY" },
	{ value: "czechia", ISO_A2: "CZ" },
	{ value: "germany", ISO_A2: "DE" },
	{ value: "djibouti", ISO_A2: "DJ" },
	{ value: "denmark", ISO_A2: "DK" },
	{ value: "dominican rep.", ISO_A2: "DO" },
	{ value: "algeria", ISO_A2: "DZ" },
	{ value: "ecuador", ISO_A2: "EC" },
	{ value: "egypt", ISO_A2: "EG" },
	{ value: "eritrea", ISO_A2: "ER" },
	{ value: "spain", ISO_A2: "ES" },
	{ value: "estonia", ISO_A2: "EE" },
	{ value: "ethiopia", ISO_A2: "ET" },
	{ value: "finland", ISO_A2: "FI" },
	{ value: "fiji", ISO_A2: "FJ" },
	{ value: "falkland is.", ISO_A2: "FK" },
	{ value: "france", ISO_A2: "FR" },
	{ value: "gabon", ISO_A2: "GA" },
	{ value: "united kingdom", ISO_A2: "GB" },
	{ value: "georgia", ISO_A2: "GE" },
	{ value: "ghana", ISO_A2: "GH" },
	{ value: "guinea", ISO_A2: "GN" },
	{ value: "gambia", ISO_A2: "GM" },
	{ value: "guinea-bissau", ISO_A2: "GW" },
	{ value: "eq. guinea", ISO_A2: "GQ" },
	{ value: "greece", ISO_A2: "GR" },
	{ value: "greenland", ISO_A2: "GL" },
	{ value: "guatemala", ISO_A2: "GT" },
	{ value: "guyana", ISO_A2: "GY" },
	{ value: "honduras", ISO_A2: "HN" },
	{ value: "croatia", ISO_A2: "HR" },
	{ value: "haiti", ISO_A2: "HT" },
	{ value: "hungary", ISO_A2: "HU" },
	{ value: "indonesia", ISO_A2: "ID" },
	{ value: "india", ISO_A2: "IN" },
	{ value: "ireland", ISO_A2: "IE" },
	{ value: "iran", ISO_A2: "IR" },
	{ value: "iraq", ISO_A2: "IQ" },
	{ value: "iceland", ISO_A2: "IS" },
	{ value: "israel", ISO_A2: "IL" },
	{ value: "italy", ISO_A2: "IT" },
	{ value: "jamaica", ISO_A2: "JM" },
	{ value: "jordan", ISO_A2: "JO" },
	{ value: "japan", ISO_A2: "JP" },
	{ value: "kazakhstan", ISO_A2: "KZ" },
	{ value: "kenya", ISO_A2: "KE" },
	{ value: "kyrgyzstan", ISO_A2: "KG" },
	{ value: "cambodia", ISO_A2: "KH" },
	{ value: "south korea", ISO_A2: "KR" },
	{ value: "kosovo", ISO_A2: "XK" },
	{ value: "kuwait", ISO_A2: "KW" },
	{ value: "laos", ISO_A2: "LA" },
	{ value: "lebanon", ISO_A2: "LB" },
	{ value: "liberia", ISO_A2: "LR" },
	{ value: "libya", ISO_A2: "LY" },
	{ value: "sri lanka", ISO_A2: "LK" },
	{ value: "lesotho", ISO_A2: "LS" },
	{ value: "lithuania", ISO_A2: "LT" },
	{ value: "luxembourg", ISO_A2: "LU" },
	{ value: "latvia", ISO_A2: "LV" },
	{ value: "morocco", ISO_A2: "MA" },
	{ value: "moldova", ISO_A2: "MD" },
	{ value: "madagascar", ISO_A2: "MG" },
	{ value: "mexico", ISO_A2: "MX" },
	{ value: "macedonia", ISO_A2: "MK" },
	{ value: "mali", ISO_A2: "ML" },
	{ value: "myanmar", ISO_A2: "MM" },
	{ value: "montenegro", ISO_A2: "ME" },
	{ value: "mongolia", ISO_A2: "MN" },
	{ value: "mozambique", ISO_A2: "MZ" },
	{ value: "mauritania", ISO_A2: "MR" },
	{ value: "malawi", ISO_A2: "MW" },
	{ value: "malaysia", ISO_A2: "MY" },
	{ value: "namibia", ISO_A2: "NA" },
	{ value: "new caledonia", ISO_A2: "NC" },
	{ value: "niger", ISO_A2: "NE" },
	{ value: "nigeria", ISO_A2: "NG" },
	{ value: "nicaragua", ISO_A2: "NI" },
	{ value: "netherlands", ISO_A2: "NL" },
	{ value: "norway", ISO_A2: "NO" },
	{ value: "nepal", ISO_A2: "NP" },
	{ value: "new zealand", ISO_A2: "NZ" },
	{ value: "oman", ISO_A2: "OM" },
	{ value: "pakistan", ISO_A2: "PK" },
	{ value: "panama", ISO_A2: "PA" },
	{ value: "peru", ISO_A2: "PE" },
	{ value: "philippines", ISO_A2: "PH" },
	{ value: "papua new guinea", ISO_A2: "PG" },
	{ value: "poland", ISO_A2: "PL" },
	{ value: "puerto rico", ISO_A2: "PR" },
	{ value: "north korea", ISO_A2: "KP" },
	{ value: "portugal", ISO_A2: "PT" },
	{ value: "paraguay", ISO_A2: "PY" },
	{ value: "palestine", ISO_A2: "PS" },
	{ value: "qatar", ISO_A2: "QA" },
	{ value: "romania", ISO_A2: "RO" },
	{ value: "russia", ISO_A2: "RU" },
	{ value: "rwanda", ISO_A2: "RW" },
	{ value: "w. sahara", ISO_A2: "EH" },
	{ value: "saudi arabia", ISO_A2: "SA" },
	{ value: "sudan", ISO_A2: "SD" },
	{ value: "s. sudan", ISO_A2: "SS" },
	{ value: "senegal", ISO_A2: "SN" },
	{ value: "solomon is.", ISO_A2: "SB" },
	{ value: "sierra leone", ISO_A2: "SL" },
	{ value: "el salvador", ISO_A2: "SV" },
	{ value: "somaliland", ISO_A2: "-99" },
	{ value: "somalia", ISO_A2: "SO" },
	{ value: "serbia", ISO_A2: "RS" },
	{ value: "suriname", ISO_A2: "SR" },
	{ value: "slovakia", ISO_A2: "SK" },
	{ value: "slovenia", ISO_A2: "SI" },
	{ value: "sweden", ISO_A2: "SE" },
	{ value: "swaziland", ISO_A2: "SZ" },
	{ value: "syria", ISO_A2: "SY" },
	{ value: "chad", ISO_A2: "TD" },
	{ value: "togo", ISO_A2: "TG" },
	{ value: "thailand", ISO_A2: "TH" },
	{ value: "tajikistan", ISO_A2: "TJ" },
	{ value: "turkmenistan", ISO_A2: "TM" },
	{ value: "timor-leste", ISO_A2: "TL" },
	{ value: "trinidad and tobago", ISO_A2: "TT" },
	{ value: "tunisia", ISO_A2: "TN" },
	{ value: "turkey", ISO_A2: "TR" },
	{ value: "taiwan", ISO_A2: "TW" },
	{ value: "tanzania", ISO_A2: "TZ" },
	{ value: "uganda", ISO_A2: "UG" },
	{ value: "ukraine", ISO_A2: "UA" },
	{ value: "uruguay", ISO_A2: "UY" },
	{ value: "united states of america", ISO_A2: "US" },
	{ value: "uzbekistan", ISO_A2: "UZ" },
	{ value: "venezuela", ISO_A2: "VE" },
	{ value: "vietnam", ISO_A2: "VN" },
	{ value: "vanuatu", ISO_A2: "VU" },
	{ value: "yemen", ISO_A2: "YE" },
	{ value: "south africa", ISO_A2: "ZA" },
	{ value: "zambia", ISO_A2: "ZM" },
	{ value: "zimbabwe", ISO_A2: "ZW" },
];
